iwatched/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path


urlpatterns = [
    path('main/', include('main.urls')),
    path('api/', include('main.api.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/api/urls.py
from django.urls import path
from rest_framework.authtoken.views import ObtainAuthToken

from main.api.api_views import (
    FilmsListAPIView,
    FilmDetailAPIView,
    RegisterAPIView,
    LogoutAPIView,
    ProfileAPIView,
    CommentCreateAPIView,
    CreateUpdateRateAPIView,
    AddFilmToListAPIView,
    PrivateStatusAPIView,
)

urlpatterns = [
    path('films/', FilmsListAPIView.as_view(), name='films'),
    path('films/<int:film_id>/', FilmDetailAPIView.as_view(), name='film'),
    path('films/<int:film_id>/create-comment', CommentCreateAPIView.as_view(), name='comment'),
    path('films/<int:film_id>/rate', CreateUpdateRateAPIView.as_view(), name='rate'),
    path('films/<int:film_id>/add-to-list/<int:films_list_id>', AddFilmToListAPIView.as_view(), name='add_to_list'),
    path('register/', RegisterAPIView.as_view(), name='register'),
    path('login/', ObtainAuthToken.as_view(), name='login'),
    path('logout/', LogoutAPIView.as_view(), name='logout'),
    path('profile/<int:user_id>/', ProfileAPIView.as_view(), name='profile'),
    path('profile/<int:user_id>/private-status/<int:films_list_id>', PrivateStatusAPIView.as_view(), name='private'),
]

main/urls.py
from django.urls import path
from main import views

app_name = 'main'
urlpatterns = [
    path('', views.AboutView.as_view(), name='about'),
    path('films/', views.FilmsListView.as_view(), name='films'),
]

main/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from main.constants import VALUES_CHOICES, FILM_LIST_TYPES


class Franchise(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Genre(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Film(models.Model):
    name = models.CharField(max_length=200)
    synopsis = models.TextField()
    genre = models.ManyToManyField(Genre, blank=True, related_name='films')
    poster = models.ImageField(null=True, blank=True)
    release_date = models.DateField(null=True, blank=True)
    franchise = models.ForeignKey(Franchise, null=True, blank=True, on_delete=models.SET_NULL, related_name='films')

    def __str__(self):
        return f'{self.name} (object ID {self.id})'

    @property
    def rating(self):
        return self.rates.all().aggregate(models.Avg('value'))['value__avg']


class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)

    def __str__(self):
        return f'{self.email}'


class FilmsList(models.Model):
    type = models.IntegerField(choices=FILM_LIST_TYPES)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='films_lists')
    film = models.ManyToManyField(Film, blank=True, related_name='films_lists')
    private = models.BooleanField(default=True)

    class Meta:
        unique_together = ['user', 'type']

    def __str__(self):
        return f'Films list by - {self.user}. Type: {self.type}'


class Comment(models.Model):
    film = models.ForeignKey(Film, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True, related_name='comments')
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment object ID {self.id}'


class Rate(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='rates')
    film = models.ForeignKey(Film, on_delete=models.CASCADE, related_name='rates')
    value = models.IntegerField(choices=VALUES_CHOICES)

    class Meta:
        unique_together = ['user', 'film']

    def __str__(self):
        return f'{self.value} star(s) rate by {self.user} for {self.film}'

main/views.py
from django.views.generic import ListView, TemplateView

from main.models import Film


class FilmsListView(ListView):
    template_name = 'main/films_list.html'
    model = Film
    queryset = Film.objects.order_by('-id')


class AboutView(TemplateView):
    template_name = 'main/about.html'

main/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}iWatched{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
    <aside>
        <img src="{% static 'main/img/logo.png' %}" alt="logo">
        <ul>
            <a href="{% url 'main:films' %}"><li><i class="fas fa-film"></i> Films</li></a>
            <a href="{% url 'main:about' %}"><li><i class="fas fa-info-circle"></i> About</li></a>
        </ul>
    </aside>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

main/templates/main/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock %}

{% block content %}
    <div class="features">
        <h1>About this website</h1>
        <p>This is the film's website where you can comment, rate film's, create your own films lists
            of watched films or films that you want to watch in near future and share your lists with other people.</p>
    </div>
{% endblock %}

main/templates/main/films_list.html
{% extends 'base.html' %}

{% block title %}All films{% endblock %}

{% block content %}
    <div class="features" style="color:blueviolet">

        {% if object_list %}

            {% for film in object_list %}
                <div class="card mb-3" style="border-width:5px; border-color:blueviolet; background-color:blueviolet">
                    <a class="card-block stretched-link text-decoration-none" href="{% url 'main:films' %}">
                        {% if film.poster %}
                            <img src="{{film.poster.url}}" class="card-img-top" alt="poster" height="500">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title text-white">{{film.name}}</h5>
                            <p class="card-text text-white">{{film.synopsis|truncatechars:100}}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}

        {% else %}
            Films not found.
        {% endif %}
    </div>
{% endblock %}